# Generated by Django 5.2.3 on 2025-07-21 15:09

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Alborz', 'البرز'), ('Ardabil', 'اردبیل'), ('East Azerbaijan', 'آذربایجان شرقی'), ('West Azerbaijan', 'آذربایجان غربی'), ('Bushehr', 'بوشهر'), ('Chaharmahal and Bakhtiari', 'چهارمحال و بختیاری'), ('Fars', 'فارس'), ('Gilan', 'گیلان'), ('Golestan', 'گلستان'), ('Hamadan', 'همدان'), ('Hormozgan', 'هرمزگان'), ('Ilam', 'ایلام'), ('Isfahan', 'اصفهان'), ('Kerman', 'کرمان'), ('Kermanshah', 'کرمانشاه'), ('Khuzestan', 'خوزستان'), ('Kohgiluyeh and Boyer-Ahmad', 'کهگیلویه و بویراحمد'), ('Kurdistan', 'کردستان'), ('Lorestan', 'لرستان'), ('Markazi', 'مرکزی'), ('Mazandaran', 'مازندران'), ('North Khorasan', 'خراسان شمالی'), ('Razavi Khorasan', 'خراسان رضوی'), ('South Khorasan', 'خراسان جنوبی'), ('Qazvin', 'قزوین'), ('Qom', 'قم'), ('Semnan', 'سمنان'), ('Sistan and Baluchestan', 'سیستان و بلوچستان'), ('Tehran', 'تهران'), ('Yazd', 'یزد'), ('Zanjan', 'زنجان')], max_length=30, verbose_name='استان')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('street', models.CharField(max_length=20, verbose_name='خیابان')),
                ('alley', models.CharField(max_length=20, verbose_name='کوچه')),
                ('number', models.CharField(max_length=3, verbose_name='پلاک')),
                ('zip_code', models.CharField(max_length=10, verbose_name='کدپستی')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address', verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سایر مشخصات',
            },
        ),
    ]
