# Generated by Django 5.2.3 on 2025-07-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'سایر مشخصات'},
        ),
    ]
