# Generated by Django 5.2.3 on 2025-07-21 15:09

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('discount', models.IntegerField(verbose_name='میزان تخفیف')),
                ('start', models.DateTimeField(verbose_name='شروع تخفیف')),
                ('end', models.DateTimeField(verbose_name='پایان تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product_images_upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='نام')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='عنوان')),
                ('main_image', models.ImageField(upload_to=store.models.product_main_image_upload_to, verbose_name='تصویر اصلی')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description_brief', models.TextField(verbose_name='توضیحات')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('slug', models.SlugField(max_length=250)),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ/زمان ایجاد')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='دسته\u200cبندی')),
                ('discount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.discount', verbose_name='تخفیف')),
                ('images', models.ManyToManyField(to='store.image', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ/زمان ایجاد')),
                ('total_price', models.IntegerField(verbose_name='مجموع قیمت\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='store.product', verbose_name='کالاها')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-creation'],
            },
        ),
    ]
