# Generated by Django 5.2.3 on 2025-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'ثابت')], max_length=10, verbose_name='نوع تخفیف'),
        ),
    ]
