name: hoshma-shop

services:

  redis:
    image: redis
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hoshma-shop-img
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py runserver 0.0.0.0:8000"
    container_name: hoshma-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file: ".env"
    depends_on:
      - redis
