name: online-store

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: online-store-img
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    container_name: backend-store
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file: ".env"
