# Generated by Django 5.2.5 on 2025-08-18 16:04

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Tehran', 'Tehran'), ('Alborz', 'Alborz'), ('Fars', 'Fars'), ('Khorasan_Razavi', 'Khorasan Razavi'), ('Kermanshah', 'Kermanshah'), ('Isfahan', 'Isfahan'), ('Yazd', 'Yazd'), ('Hamedan', 'Hamedan'), ('Kerman', 'Kerman'), ('Khuzestan', 'Khuzestan'), ('Gilan', 'Gilan'), ('Mazandaran', 'Mazandaran'), ('Zanjan', 'Zanjan'), ('Golestan', 'Golestan'), ('Bushehr', 'Bushehr'), ('Semnan', 'Semnan'), ('Ardebil', 'Ardebil'), ('Qazvin', 'Qazvin'), ('Qom', 'Qom'), ('South_Khorasan', 'South Khorasan'), ('North_Khorasan', 'North Khorasan'), ('Markazi', 'Markazi'), ('Kohgiluyeh_Boyerahmad', 'Kohgiluyeh and Boyerahmad'), ('Chaharmahal_Bakhtiari', 'Chaharmahal and Bakhtiari'), ('Ilam', 'Ilam'), ('West_Azerbaijan', 'West Azerbaijan'), ('East_Azerbaijan', 'East Azerbaijan'), ('Lorestan', 'Lorestan'), ('Sistan_Baluchestan', 'Sistan and Baluchestan'), ('Hormozgan', 'Hormozgan')], max_length=30, verbose_name='Province')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('street', models.CharField(max_length=20, verbose_name='Street')),
                ('alley', models.CharField(max_length=20, verbose_name='Alley')),
                ('number', models.CharField(max_length=3, verbose_name='Number')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^09\\d{9}$')], verbose_name='Phone')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modification')),
                ('products', models.ManyToManyField(to='shop.product', verbose_name='Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-creation'],
            },
        ),
    ]
