PROVINCE_CHOICES = [
    ("Alborz", "البرز"),
    ("Ardabil", "اردبیل"),
    ("East Azerbaijan", "آذربایجان شرقی"),
    ("West Azerbaijan", "آذربایجان غربی"),
    ("Bushehr", "بوشهر"),
    ("Chaharmahal and Bakhtiari", "چهارمحال و بختیاری"),
    ("Fars", "فارس"),
    ("Gilan", "گیلان"),
    ("Golestan", "گلستان"),
    ("Hamadan", "همدان"),
    ("Hormozgan", "هرمزگان"),
    ("Ilam", "ایلام"),
    ("Isfahan", "اصفهان"),
    ("Kerman", "کرمان"),
    ("Kermanshah", "کرمانشاه"),
    ("Khuzestan", "خوزستان"),
    ("Kohgiluyeh and Boyer-Ahmad", "کهگیلویه و بویراحمد"),
    ("Kurdistan", "کردستان"),
    ("Lorestan", "لرستان"),
    ("Markazi", "مرکزی"),
    ("Mazandaran", "مازندران"),
    ("North Khorasan", "خراسان شمالی"),
    ("Razavi Khorasan", "خراسان رضوی"),
    ("South Khorasan", "خراسان جنوبی"),
    ("Qazvin", "قزوین"),
    ("Qom", "قم"),
    ("Semnan", "سمنان"),
    ("Sistan and Baluchestan", "سیستان و بلوچستان"),
    ("Tehran", "تهران"),
    ("Yazd", "یزد"),
    ("Zanjan", "زنجان"),
]
