# Generated by Django 5.2.5 on 2025-09-07 13:23

import django.db.models.deletion
import shop.models
import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], max_length=10, verbose_name='Type')),
                ('amount', models.PositiveIntegerField(validators=[shop.validators.validate_positive_value], verbose_name='Amount')),
                ('start', models.DateTimeField(validators=[shop.validators.validate_not_in_past], verbose_name='Start')),
                ('end', models.DateTimeField(validators=[shop.validators.validate_not_in_past], verbose_name='End')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description_brief', models.TextField(verbose_name='Brief Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modification')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('hierarchy', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='main_image', serialize=False, to='shop.product')),
                ('image', models.ImageField(upload_to=shop.models.product_main_image_upload_to, verbose_name='Main Image')),
                ('alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Main Image',
                'verbose_name_plural': 'Main Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.discount', verbose_name='Discount'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.product_images_upload_to, verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='shop.tag'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['hierarchy'], name='shop_catego_hierarc_e1353f_idx'),
        ),
    ]
