# Generated by Django 5.2.5 on 2025-08-18 16:04

import django.core.validators
import django.db.models.deletion
import shop.models
import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], max_length=10, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('start', models.DateTimeField(validators=[shop.validators.not_in_past_validator], verbose_name='Start')),
                ('end', models.DateTimeField(validators=[shop.validators.not_in_past_validator], verbose_name='End')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('hierarchy', models.IntegerField(editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('main_image', models.ImageField(upload_to=shop.models.product_main_image_upload_to, verbose_name='Main Image')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Negative inputs are not allowed for this field.')], verbose_name='Price')),
                ('description_brief', models.TextField(verbose_name='Brief Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Negative inputs are not allowed for this field.')], verbose_name='Stock')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.discount', verbose_name='Discount')),
                ('tags', models.ManyToManyField(related_name='products', to='shop.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.product_images_upload_to, verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['hierarchy'], name='shop_catego_hierarc_e1353f_idx'),
        ),
    ]
