# Generated by Django 5.2.5 on 2025-09-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
